### ISSUE TITLE
Crash in find_morphism

### ISSUE THREAD

**Issue by fieker** [Nemocas/Nemo.jl#969] opened 2021-02-09 13:43 UTC
F = FiniteField(13, 1, "a")[1]
k = GF(13)
kt, t = PolynomialRing(k, "t")
G = FiniteField(t+1, "b")[1]
Nemo.find_morphism(F, G)

signal (11): Segmentation fault
in expression starting at REPL[9]:1
n_invmod at /workspace/srcdir/flint2-2.7.0/ulong_extras.h:326 [inlined]

**Comment by wbhart** [comment] 2021-02-09 17:13
Could @defeo or @erou look at this. It seems to be crashing in embedding code. Here is the relevant part of the stack trace:

```
signal (11): Segmentation fault
in expression starting at REPL[6]:1
n_invmod at /workspace/srcdir/flint2-2.7.0/ulong_extras.h:326 [inlined]
fq_nmod_ctx_init_modulus at /workspace/srcdir/flint2-2.7.0/fq_nmod/ctx_init_modulus.c:46
fq_nmod_embed_matrices at /workspace/srcdir/flint2-2.7.0/fq_embed_templates/matrices.c:153
embed_matrices at /home/wbhart/.julia/dev/Nemo/src/flint/fq_nmod_embed.jl:60
embed_any at /home/wbhart/.julia/dev/Nemo/src/embedding/embedding.jl:168 [inlined]
find_morphism at /home/wbhart/.julia/dev/Nemo/src/embedding/embedding.jl:220
```

**Comment by erou** [comment] 2021-02-09 17:29
Hello,

This happens because the user is not supposed to directly call `find_morphism`. There is no error if the function `embed` is used. Maybe that is not clear enough in the code but there is no guaranty that the embedding framework still works if the user uses anything but the `embed` function.

In this particular case, I did not look deeply into it, but I think that the issue is simply that the C functions are not supposed to work with degree one finite fields.

**Comment by erou** [comment] 2021-02-09 17:39
What I mean is that the functions that are not exported (such as find_morphism, transitive_closure, etc.) are supposed to be used internally only. We may want to warn the user about that a little more, or change the code so that these functions can be used safely.

**Comment by fieker** [comment] 2021-02-10 07:36
Problem is embed is not working in the general situation. @sircana has a patch, but it is waiting due to breaking changes. Problem ist the internal logic is flawed...:
(might require Oscar/ Hecke to set up)
F = FiniteField(13, 4, "s")[1]
K1 = FiniteField(minpoly(rand(F)), "r1")[1]
K2 = FiniteField(minpoly(rand(F)), "r2")[1]
K3 = FiniteField(minpoly(rand(F)), "r3")[1]
K4 = FiniteField(minpoly(rand(F)), "r4")[1]
embed(K1, F);
embed(K2, F);
embed(K3, F);
embed(K4, F);
length(F.subfields[4]) -> 39 or so. The number os subfields seems to grow exponentially.. AND
julia> length(Set(domain(x) for x = F.subfields[4]))
4

as expected....

**Comment by erou** [comment] 2021-02-10 09:07
Yes you are right, there is indeed a problem with the embed framework. I read the code and saw a typo that is responsible for this. I was able to reproduce your example and I now obtain 4 instead of 39. I'll make a pull request.

**Comment by wbhart** [comment] 2021-02-13 00:46
Should be fixed now. @fieker perhaps you can confirm and close the issue if you are satisfied.

**Comment by wbhart** [comment] 2021-07-29 16:25
Guess it's fixed.

**Closed by wbhart** 2021-07-29 16:25 UTC
