### ISSUE TITLE
Avoid void pointers

### ISSUE THREAD

**Issue by jonas-schulze** [Nemocas/Nemo.jl#1920] opened 2024-10-24 12:46 UTC
Would it be feasible to refactor the [`coeffs` and `exps`](https://github.com/Nemocas/Nemo.jl/blob/633112d66e84cf3341bd56e4b1ddd8eebac60a62/src/flint/FlintTypes.jl#L1358-L1359) fields of `QQMPolyRingElem` to not be `Ptr{Nothing}`?

I did not spend too much time to understand how these fields are used or initialized, but assuming they are coming from some non-Julia library,
would it be possible to replace them by some `Ref{SomeNewType}` that wraps that non-Julia type? See `CpuTopology` in [liblikwid](https://github.com/RRZE-HPC/likwid/blob/v5.1/src/includes/likwid.h#L370-L380) and [LIKWID.jl](https://github.com/JuliaPerf/LIKWID.jl/blob/v0.4.4/src/LibLikwid.jl#L640-L651) for an example.

See https://github.com/oscar-system/Oscar.jl/issues/4242 for some background.

**Comment by lgoettgens** [comment] 2024-10-24 16:27
Your idea to add new types for these things is already the topic of https://github.com/Nemocas/Nemo.jl/issues/1875.
However, I am not certain that this (already big!) change alone makes it possible to use JLD2 for serialization, as there additionally is the memory these pointers point to, and this memory is managed by the C library FLINT (in particular not by julia by any means).
You can try to use JLD2 again once https://github.com/Nemocas/Nemo.jl/issues/1875 is resolved, but I won't promise you anything.

(I would propose to close this as a duplicate of https://github.com/Nemocas/Nemo.jl/issues/1875 @thofma @fingolfin )

**Comment by thofma** [comment] 2024-10-24 17:09
No, there are several reasons why this won't work. Any serialization/deserialization approach which tries to directly access/set internal fields is doomed to fail for non-trivial things. Here are a few reasons:
1.  The fields themselves are not public. They might change without notice. They might change in a way that deserialization works but gives silently different/wrong results.
2. The data of the fields alone do not have enough information to serialize/deserialize an object. The important information is how they work together. For example, a polynomial might have two fields: `coeff::Ptr{Something}` and `length::Int`. Without knowing that `coeff` points to a chunk of memory of a specific size (given by interpreting `length` correctly) serialization must fail.
3. Because of 2), the only way to serialize/deserialize the data is to know how the fields are related and what they mean. But again this is not public.
4. The only way to serialize/deserialize the data is to use the interface. But this needs no change to the layout of the objects themselves.

**Closed** 2024-10-24 17:11 UTC
