### ISSUE TITLE
ERROR: munmap_chunk(): invalid pointer

### ISSUE THREAD

**Issue by abagciphys** [Nemocas/Nemo.jl#944] opened 2021-01-06 22:46 UTC
Nemo does not contain all the special functions defined in Arb library. Defining one needed outside the /src folder via ccall with a form that similar to Nemo lead to such an error. The previous version of the repository was more flexible with a previous version of Julia and arb-devel.
My code does not work any-more and the problem seems not only about replacing the prec(r) with a precision(r)...

**Comment by thofma** [comment] 2021-01-07 07:54
Can you post an example and the error message?

**Comment by abagciphys** [comment] 2021-01-07 18:41
munmap_chunk(): invalid pointer

signal (6): Aborted
in expression starting at REPL[2]:1
gsignal at /lib64/libc.so.6 (unknown line)
abort at /lib64/libc.so.6 (unknown line)
__libc_message at /lib64/libc.so.6 (unknown line)
malloc_printerr at /lib64/libc.so.6 (unknown line)
munmap_chunk at /lib64/libc.so.6 (unknown line)
jl_gc_counted_free_with_size at /buildworker/worker/package_linux64/build/src/gc.c:3254
arb_clear at /workspace/srcdir/arb-2.19.0/arb/clear.c:20
_arb_clear_fn at /home/abagci.phys/.julia/packages/Nemo/tdXHv/src/arb/ArbTypes.jl:148
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2214 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2398
jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1690 [inlined]
run_finalizer at /buildworker/worker/package_linux64/build/src/gc.c:277
jl_gc_run_finalizers_in_list at /buildworker/worker/package_linux64/build/src/gc.c:363
run_finalizers at /buildworker/worker/package_linux64/build/src/gc.c:391 [inlined]
jl_gc_collect at /buildworker/worker/package_linux64/build/src/gc.c:3127
maybe_collect at /buildworker/worker/package_linux64/build/src/gc.c:827 [inlined]
jl_gc_pool_alloc at /buildworker/worker/package_linux64/build/src/gc.c:1142
arb at /home/abagci.phys/.julia/packages/Nemo/tdXHv/src/arb/ArbTypes.jl:106 [inlined]
ArbField at /home/abagci.phys/.julia/packages/Nemo/tdXHv/src/arb/arb.jl:2071 [inlined]
* at /home/abagci.phys/.julia/packages/Nemo/tdXHv/src/arb/arb.jl:614
* at ./operators.jl:538
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2214 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2398
AuxiliaryG at /home/abagci.phys/Source_files_30_09_2020/special_functions.jl:885
unknown function (ip: 0x7f7949604ee4)
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2231 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2398
jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1690 [inlined]
do_call at /buildworker/worker/package_linux64/build/src/interpreter.c:117
eval_value at /buildworker/worker/package_linux64/build/src/interpreter.c:206
eval_stmt_value at /buildworker/worker/package_linux64/build/src/interpreter.c:157 [inlined]
eval_body at /buildworker/worker/package_linux64/build/src/interpreter.c:566
jl_interpret_toplevel_thunk at /buildworker/worker/package_linux64/build/src/interpreter.c:660
jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:840
jl_toplevel_eval_flex at /buildworker/worker/package_linux64/build/src/toplevel.c:790
jl_toplevel_eval_in at /buildworker/worker/package_linux64/build/src/toplevel.c:883
eval at ./boot.jl:331
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2214 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2398
eval_user_input at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/REPL/src/REPL.jl:134
repl_backend_loop at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/REPL/src/REPL.jl:195
start_repl_backend at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/REPL/src/REPL.jl:180
#run_repl#37 at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/REPL/src/REPL.jl:292
run_repl at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.5/REPL/src/REPL.jl:288
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2231 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2398
#807 at ./client.jl:399
jfptr_YY.807_45002.clone_1 at /home/abagci.phys/julia-1.5.3/lib/julia/sys.so (unknown line)
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2214 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2398
jl_apply at /buildworker/worker/package_linux64/build/src/julia.h:1690 [inlined]
do_apply at /buildworker/worker/package_linux64/build/src/builtins.c:655
jl_f__apply_latest at /buildworker/worker/package_linux64/build/src/builtins.c:705
#invokelatest#1 at ./essentials.jl:710 [inlined]
invokelatest at ./essentials.jl:709 [inlined]
run_main_repl at ./client.jl:383
exec_options at ./client.jl:313
_start at ./client.jl:506
jfptr__start_53898.clone_1 at /home/abagci.phys/julia-1.5.3/lib/julia/sys.so (unknown line)
_jl_invoke at /buildworker/worker/package_linux64/build/src/gf.c:2214 [inlined]
jl_apply_generic at /buildworker/worker/package_linux64/build/src/gf.c:2398
unknown function (ip: 0x401931)
unknown function (ip: 0x401533)
__libc_start_main at /lib64/libc.so.6 (unknown line)
unknown function (ip: 0x4015d4)
Allocations: 5417858 (Pool: 5416857; Big: 1001); GC: 4
Aborted (core dumped)


The line 855 in "AuxiliaryG at /home/abagci.phys/Source_files_30_09_2020/special_functions.jl:885" is the vectorized form of the Beta functions. The both Beta functions and its vectorized form work fine in their own. In addition they had no problem previously the "AuxiliaryG" was in fine....The file including this function run over a "math.jl" file written based on the Nemo via "ccall".

thank you...

**Comment by thofma** [comment] 2021-01-07 18:45
Can you provide the exact function call together with the input? Otherwise this is almost impossible to debug.

**Comment by abagciphys** [comment] 2021-01-11 01:10
It is a large code...simply it include confluent hypergeometric functions, exponentials integralsi incomplete and complete beta functions...The problem may be in converting the complex balls to real balls. Or using this type of function (Nemo does not involve it) 

function Beta(a::arb, b::arb, x::arb)
    z = parent(x)()
    ccall((:arb_hypgeom_beta_lower, :libarb), Nothing,(Ref{arb}, Ref{arb}, Ref{arb}, Ref{arb}, Int, Int),
    z, a, b, x, 0, parent(x).prec)
    return z
end
...
function ExpIntegralE(x::arb, y::arb)
    z = parent(x)()
    ccall((:arb_hypgeom_expint, :libarb), Nothing, (Ref{arb}, Ref{arb}, Ref{arb}, Int),
    z, x, y, parent(x).prec)
    return z
end

It works actually themselves...The strange thing is that my all code without en error was working with the previous version of "Nemo-0.9.0" but no way to install this package any more since the clone links to newest one...
I dont know, the Nemo package quite useful especially for mathematical computing but to be honest need a bit more performance  to be comprehensive for all arb functions...Else it seems personal performance with a mediocre computer skill not enough to follow-modify correctly the written code to new version of the package...

**Comment by abagciphys** [comment] 2021-01-11 01:34
I just find a way to install this version "Nemo v0.18.4 `https://github.com/wbhart/Nemo.jl.git#master`" let me a note for you it working well...With this version my problem already has been solved.

**Comment by wbhart** [comment] 2021-01-11 01:39
Great to hear the problem is already gone in the latest version. I will now close the issue.

**Closed by wbhart** 2021-01-11 01:39 UTC

**Comment by thofma** [comment] 2021-01-11 08:46
I think it is gone because he went back to 0.18.4?

Anyway, @abagciphys, there is one thing you could try. Can you replace the ":libarb" in the ccall's by "Nemo.libarb" and try again?

Alternatively, you could make the code public or send me the code privately so that we can have a closer look.

**Comment by abagciphys** [comment] 2021-01-11 10:10
I have a paper "https://doi.org/10.1007/s12210-020-00953-3" and yes the results there obtained using Nemo. The citiation was as "For accuracy, only an additional computer algebra package, called Nemo Fieker et al. (2017) is required. This package is based on C libraries such as FLINT, ANTIC, Arb, Pari and Singular. It has a module system which is use to provide access to Nemo. It is imported and used all exported func-tionality by simply type using Nemo." 

I will try the "Nemo.libarb" and send the piece of code that closely related with the problem, privately. After all right yes I wish to make the code public...
Than you...

**Comment by abagciphys** [comment] 2021-01-11 10:51
"Nemo.libarb" works in the present version of the Nemo... But not needed in fact in a version Nemo v0.18.4 so all right now...

**Comment by thofma** [comment] 2021-01-11 10:54
Good to hear. Feel free to open another issue if you encounter other problems.

**Comment by abagciphys** [comment] 2021-01-11 11:02
Thank you for your interest and for the "Nemo" package happy to have it.
