### ISSUE TITLE
Access violation in fmpz-clear

### ISSUE THREAD

**Issue by PeterLuschny** [Nemocas/Nemo.jl#585] opened 2019-04-24 08:54 UTC
An old problem is back. To make it easier to track, I made it a mini-project that can also be tracked on Appveyor.

https://github.com/PeterLuschny/NemoTest
https://ci.appveyor.com/project/PeterLuschny/nemotest/build/job/orn1u35lfa0gg8d3

Peter

**Comment by thofma** [comment] 2019-04-24 10:19
I have rebuild the binaries with different flags as suggested by @wbhart in https://github.com/Nemocas/Nemo.jl/issues/499.

Can you try with the following branch https://github.com/Nemocas/Nemo.jl/tree/th/reentrant?

**Comment by wbhart** [comment] 2019-04-24 12:09
Perhaps we should add a build option to the environment, e.g. FLINT_REENTRANT which when set causes the reentrant version of Flint to be downloaded instead? This would make debugging a little easier, though of course it will cause the user some trouble to rebuild when we encounter a bug of this sort.

**Comment by PeterLuschny** [comment] 2019-04-24 13:10
Could you please be more specific about what you expect me to do? 
"Nemo" is referenced in exactly one line, in runtests.jl line 7:

    import Pkg; Pkg.add("Nemo")

What am I supposed to do here?

**Comment by PeterLuschny** [comment] 2019-04-24 13:11
Could you be more specific about what you expect me to do? 

"Nemo" is referenced in exactly one line, in runtests.jl line 7:

    import Pkg; Pkg.add("Nemo")

What am I supposed to do here?

**Comment by thofma** [comment] 2019-04-24 13:12
I think the following should do it:
```
Pkg.add("Nemo"); Pkg.checkout("Nemo", "th/reentrant"); Pkg.build("Nemo")
```

**Comment by PeterLuschny** [comment] 2019-04-24 13:43
ERROR: LoadError: UndefVarError: checkout not defined

In the docs I found "checkout" only in connection with LibGit2:

    repo_url = "https://github.com/Nemocas/Nemo.jl"
    repo = LibGit2.checkout!(repo_url, "th/reentrant")
	
I don't know if this makes any sense or how I should proceed.

**Comment by thofma** [comment] 2019-04-24 15:17
Sorry, I was redirected to the old docs ...

In `1.0` It is
```
Pkg.add(PackageSpec(name="Nemo", rev="th/reentrant"))
```

**Comment by PeterLuschny** [comment] 2019-04-24 17:41
Thank you! I will try that next.
Meanwhile horrible things happen here: gmp overflow!


    0
	0
	0
	0
	gmp: overflow in mpz type

	signal (22): SIGABRT
	in expression starting at C:\Users\Home\JuliaProjects\Sequences\src\BernoulliNumbers.jl:246
	crt_sig_handler at /home/Administrator/buildbot/worker/package_win64/build/src/home/Administrator/buildbot/worker/package_win64/build/src\signals-win.c:91
	raise at C:\WINDOWS\System32\msvcrt.dll (unknown line)
	abort at C:\WINDOWS\System32\msvcrt.dll (unknown line)
	.text at C:\Users\Home\.julia\packages\Nemo\bhQcy\deps\usr\bin\libgmp-10.dll (unknown line)
	.text at C:\Users\Home\.julia\packages\Nemo\bhQcy\deps\usr\bin\libgmp-10.dll (unknown line)
	flint_mpz_mul_si at /workspace/srcdir/flint2/fmpz/workspace/srcdir/flint2\gmpcompat.h:117 [inlined]
	fmpz_mul_si at /workspace/srcdir/flint2/fmpz\mul_si.c:43
	* at C:\Users\Home\.julia\packages\Nemo\bhQcy\src\flint\fmpz.jl:370
	unknown function (ip: 000000000D6A6B3E)
	jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2219
	BernoulliInt at C:\Users\Home\JuliaProjects\Sequences\src\BernoulliNumbers.jl:19
	macro expansion at C:\Users\Home\JuliaProjects\Sequences\src\BernoulliNumbers.jl:155 [inlined]
	test at C:\Users\Home\JuliaProjects\Sequences\src\BernoulliNumbers.jl:153
	main at C:\Users\Home\JuliaProjects\Sequences\src\BernoulliNumbers.jl:241
	jl_fptr_trampoline at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:1864
	jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2219
	do_call at /home/Administrator/buildbot/worker/package_win64/build/src\interpreter.c:323
	eval_value at /home/Administrator/buildbot/worker/package_win64/build/src\interpreter.c:411
	eval_stmt_value at /home/Administrator/buildbot/worker/package_win64/build/src\interpreter.c:362 [inlined]
	eval_body at /home/Administrator/buildbot/worker/package_win64/build/src\interpreter.c:755
	jl_interpret_toplevel_thunk_callback at /home/Administrator/buildbot/worker/package_win64/build/src\interpreter.c:885
	unknown function (ip: FFFFFFFFFFFFFFFE)
	unknown function (ip: 0000000006C39D1F)
	unknown function (ip: FFFFFFFFFFFFFFFF)
	jl_toplevel_eval_flex at /home/Administrator/buildbot/worker/package_win64/build/src\toplevel.c:764
	jl_eval_module_expr at /home/Administrator/buildbot/worker/package_win64/build/src\toplevel.c:179
	jl_toplevel_eval_flex at /home/Administrator/buildbot/worker/package_win64/build/src\toplevel.c:614
	jl_parse_eval_all at /home/Administrator/buildbot/worker/package_win64/build/src\ast.c:883
	include_string at .\loading.jl:1008
	#126 at C:\Users\Home\.julia\packages\Atom\E4PBh\src\eval.jl:125
	withpath at C:\Users\Home\.julia\packages\CodeTools\xGemk\src\utils.jl:30
	jl_fptr_trampoline at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:1864
	jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2219 [inlined]
	jl_apply at /home/Administrator/buildbot/worker/package_win64/build/src\julia.h:1571 [inlined]
	jl_invoke at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:56
	withpath at C:\Users\Home\.julia\packages\Atom\E4PBh\src\eval.jl:46 [inlined]
	#125 at C:\Users\Home\.julia\packages\Atom\E4PBh\src\eval.jl:122 [inlined]
	with_logstate at .\logging.jl:395
	#124 at .\logging.jl:491 [inlined]
	hideprompt at C:\Users\Home\.julia\packages\Atom\E4PBh\src\repl.jl:75
	jl_fptr_trampoline at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:1864
	jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2219
	macro expansion at C:\Users\Home\.julia\packages\Atom\E4PBh\src\eval.jl:120 [inlined]
	macro expansion at C:\Users\Home\.julia\packages\Media\ItEPc\src\dynamic.jl:24 [inlined]
	#123 at C:\Users\Home\.julia\packages\Atom\E4PBh\src\eval.jl:109
	jl_fptr_trampoline at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:1864
	jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2219
	handlemsg at C:\Users\Home\.julia\packages\Atom\E4PBh\src\comm.jl:164
	unknown function (ip: 000000000D664CE3)
	jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2219

	Julia has exited. Press Enter to start a new session.
	jl_apply at /home/Administrator/buildbot/worker/package_win64/build/src\julia.h:1571 [inlined]
	jl_f__apply at /home/Administrator/buildbot/worker/package_win64/build/src\builtins.c:556
	#19 at .\task.jl:259
	unknown function (ip: 000000000D66187A)
	jl_apply_generic at /home/Administrator/buildbot/worker/package_win64/build/src\gf.c:2219
	jl_apply at /home/Administrator/buildbot/worker/package_win64/build/src\julia.h:1571 [inlined]
	start_task at /home/Administrator/buildbot/worker/package_win64/build/src\task.c:572
	Allocations: 23573927 (Pool: 23570358; Big: 3569); GC: 51

**Comment by PeterLuschny** [comment] 2019-04-24 18:14
I am sorry to say that this did not change anything.

    https://ci.appveyor.com/project/PeterLuschny/nemotest/build/job/3408531mp509ayun
    https://github.com/PeterLuschny/NemoTest

**Comment by wbhart** [comment] 2019-04-24 18:32
I am not sure it should remove the problem. It should just make it easier to track down what the problem is. Having said that, the stack trace is not very helpful here. It looks like there is a bug in Flint somewhere that is causing corruption. Perhaps we can replicate it with an equivalent C program.

**Comment by thofma** [comment] 2019-04-25 06:34
Tried that before in #499. I could not find an equivalent C program. But maybe you have more luck.

@PeterLuschny Can you give me commit access to the NemoTest repository?

**Comment by thofma** [comment] 2019-04-25 07:21
Sorry, I mixed up the build flags yesterday.

It is now passing tests on Win64 with `--reentrant`. Does this mean we should always enable `-reentrant` on Windows @wbhart?

**Comment by wbhart** [comment] 2019-04-25 08:27
I guess so. I suspect this just masks a problem. But I have no other way to sort it out. It could also be an issue with our interface to GMP on Windows.

**Comment by thofma** [comment] 2019-04-25 09:18
Do you mean specifically GMP? It is also crashing with MPIR.

**Comment by wbhart** [comment] 2019-04-25 09:28
Ok, not that then. There is no conversion layer on Windows between MPIR and Flint. It only happens for GMP.

**Comment by PeterLuschny** [comment] 2019-04-25 09:31
The little I can say is that with Julia 0.6 none of these errors occurred. Also noteworthy is the following: In some other examples the identical code can run without errors or with errors depending on whether the functions it references are in the same module or in a different one.

**Comment by wbhart** [comment] 2019-04-25 09:32
Perhaps Julia is using threads for different modules now?

**Comment by thofma** [comment] 2019-04-25 10:01
No clue. As a stop-gap I will switch Nemo to use the reentrant binaries on Windows, OK?

**Comment by PeterLuschny** [comment] 2019-04-25 11:23
From my side: Yes, please!

I intend to register the package 'Sequences' within the next days. The package is strongly based on Nemo. Among the potential users there are certainly many Windows users. Since I will reference it afterwards often on the OEIS it must be as stable as possible. Since the OEIS has an excellent impact this could contribute to the promotion of the use of Julia and Nemo.

**Comment by wbhart** [comment] 2019-04-25 11:48
Yes, let's see how that goes.

**Comment by thofma** [comment] 2019-04-25 12:48
I will register a new version once #586 is merged.

**Comment by thofma** [comment] 2019-04-26 11:02
Version 0.13.4 just got merged, which contains the fix.

**Closed by thofma** 2019-04-26 11:02 UTC
